name = "Cobblemon Pack"
author = "dot_dash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7722673d5d24b9bf48203e9d79a95347f7296ec280d5fc46eeebf833ab58a1f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[options]
acceptable-game-versions = ["1.21"]
