name = "Cobblemon Pack"
author = "dot_dash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38f0d7864242e5394e629acbc079f3bac369b8a6bf4db23343a8ae285f7f7351"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "config/paxi/datapacks"
