name = "Cobblemon Pack"
author = "dot_dash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db76045de7198edd3281a283fc5186f86155ce51f70cb20d465f2394f6f4b74f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "config/paxi/datapacks"
