#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Sep 13 19:38:42 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.9.1 + EuphoriaPatches_1.10.1
